<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Hospital Costs Analysis}
%\VignetteDepends{ggplot2, RobStabR}
-->

# Hospitcal Costs Analysis

```{r packages}
library("robmixglm")
library("magrittr")
library("dplyr")

library(devtools)
#install_github("SmithConnor/RobStabR")
library("RobStabR")
```


```{r datawrangling}
utils::data("hospcosts", package ="robmixglm")

data = hospcosts %>% 
  dplyr::mutate(y = costs) %>% 
  dplyr::select(-id, - costs, -los)
```

## Robust Plots

```{r fitRobStab}
paperRobStab = readRDS("./../manuscript/hosp_robust_RobStab.rds") # Analysis done for the manuscript

resamplePaper = paperRobStab$bootsrap

hospRobStab = model_space(data = data,
                          B = 100,
                          m = 50,
                          nStrata = 5,
                          family = Gamma(link = log),
                          tcc = 1.5,
                          bootstraps = resamplePaper)
```

```{r rsVIP}
hospMPP = sMPP(robStab = hospRobStab)
hospMPP$plots$dev

ggplot2::ggsave("rsMPP.jpg",
                dpi = 300)

```

```{r rsMPP}
hospVIP = sVIP(robStab = hospRobStab)
hospVIP$plots$dev

ggplot2::ggsave("rsVIP.jpg",
                dpi = 300)

```

## Non-Robust Plots


```{r fitRobStabNon}
paperRobStab2 = readRDS("./../manuscript/hosp_RobStab.rds") # Analysis done for the manuscript

resamplePaper2 = paperRobStab2$bootsrap

hospRobStabNon = model_space_non(data = data,
                          B = 100,
                          m = 50,
                          nStrata = 5,
                          family = Gamma(link = log),
                          bootstraps = resamplePaper2)
```

```{r sVIP}
hospMPP = sMPP(robStab = hospRobStabNon)
hospMPP$plots$dev

ggplot2::ggsave("sMPP.jpg",
                dpi = 300)

```

```{r sMPP}
hospVIP = sVIP(robStab = hospRobStabNon)
hospVIP$plots$dev

ggplot2::ggsave("sVIP.jpg",
                dpi = 300)

```

